---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    prometheus_service: 87ca1aac-e068-11ec-a974-9bb31ed410be
    prometheus_node_exporter_service: 9da95c20-e068-11ec-b762-b38d94c6d8a8
    grafana_service: a5657b06-e068-11ec-8e1c-2f728e608caa
    beacon_service: aba073ae-e068-11ec-8b8a-ab1197e06ccd
    grafana_provisioning: ["prysm"]

  tasks:
    # prometheus service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ prometheus_service }}"
              image: "prom/prometheus:{{ stereum_static.defaults.versions.prometheus }}"
              ports:
                - 127.0.0.1:9090:9090/tcp
              env:
                CONFIG: |
                  global:
                    scrape_interval:     15s
                    evaluation_interval: 15s

                  alerting:
                    alertmanagers:
                    - static_configs:
                      - targets:
                        # - alertmanager:9093

                  rule_files:
                    # - "first_rules.yml"
                    # - "second_rules.yml"

                  scrape_configs:
                    - job_name: 'stereum-{{ beacon_service }}'
                      static_configs:
                        - targets: ['stereum-{{ beacon_service }}:8080']
                    - job_name: 'stereum-{{ prometheus_node_exporter_service }}'
                      static_configs:
                        - targets: ['stereum-{{ prometheus_node_exporter_service }}:9100']
              command: sh -c "touch /etc/prometheus/prometheus.yml &&
                              echo \"$CONFIG\" > /etc/prometheus/prometheus.yml &&
                              /bin/prometheus --config.file=/etc/prometheus/prometheus.yml"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ prometheus_service }}/data/prometheus:/prometheus"
                - "/opt/app/services/{{ prometheus_service }}/config:/etc/prometheus"
    # prometheus node-exporter service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ prometheus_node_exporter_service }}"
              image: "prom/node-exporter:{{ stereum_static.defaults.versions.node_exporter }}"
              ports: []
              env: {}
              command: []
              entrypoint: ["/bin/node_exporter"]
              user: "2000"
              volumes: []
    # grafana service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ grafana_service }}"
              image: "grafana/grafana:{{ stereum_static.defaults.versions.grafana }}"
              ports:
                - 127.0.0.1:3000:3000/tcp
              env:
                GRAFANA_INI: |
                  [auth.anonymous]
                  enabled = true
                  org_role = Admin
              command: bash -c "touch /etc/grafana/grafana.ini &&
                                echo \"$GRAFANA_INI\" > /etc/grafana/grafana.ini &&
                                /run.sh"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ grafana_service }}/grafana/provisioning:/etc/grafana/provisioning"
                - "/opt/app/services/{{ grafana_service }}/grafana/data:/var/lib/grafana"
                - "/opt/app/services/{{ grafana_service }}/grafana:/etc/grafana"

    # replace prometheus service-id into grafana's datasource.yml
    - name: replace prometheus-ID into grafana's datasource.yml
      replace:
        path: "/opt/app/services/{{ grafana_service }}/grafana/provisioning/datasources/datasource.yml"
        regexp: '  url: http:\/\/prometheus:9090'
        replace: '  url: http://stereum-{{ prometheus_service }}:9090'
      become: yes
