---
- name: Prepare
  hosts: all
  roles:
    - role: "../"
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml

  tasks:
    - name: Install pkgs for Ansible (Ubuntu)
      apt:
        update_cache: yes
        name:
          - pip
          - python3-pip
          - openjdk-8-jre-headless
          - expect
        state: present
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "CentOS"

    - name: Install keytool for creating Keystore (CentOS 8)
      raw: yum install -y java-1.8.0-openjdk
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "CentOS"

    - name: Install pip, expect (CentOS 8)
      yum:
        name:
          - python3-pip
          - expect
        state: latest
      become: true
      when: ansible_facts['distribution'] == "CentOS"

    - include_role:
        name: "setup"

    - include_role:
        name: "configure-firewall"
# EOF
