---
- name: Find service configs
  find:
    paths: "/etc/stereum/services"
  register: service_config_files

- name: Include Prysm Changes
  include_tasks: ejector_changes.yaml
  loop: "{{ service_config_files.files }}"
  loop_control:
    loop_var: config_file

- name: Include Erigon Changes
  include_tasks: erigon_changes.yaml
  loop: "{{ service_config_files.files }}"
  loop_control:
    loop_var: config_file

- name: Include SSV Changes
  include_tasks: ssv_changes.yaml
  loop: "{{ service_config_files.files }}"
  loop_control:
    loop_var: config_file
