---
- include_tasks: "2.0-rc3/updates-20-rc3.yaml"
  ignore_errors: yes

- include_tasks: "2.0-rc6/updates-20-rc6.yaml"
  ignore_errors: yes

- include_tasks: "2.0-rc7/updates-20-rc7.yaml"
  ignore_errors: yes

- include_tasks: "2.0-rc9/updates-20-rc9.yaml"
  ignore_errors: yes

- include_tasks: "2.0-rc10/updates-20-rc10.yaml"
  ignore_errors: yes

- include_tasks: "2.0-rc11/updates-20-rc11.yaml"
  ignore_errors: yes

# EOF
