---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "update-stereum--full--ubuntu-2204"
    server_type: cpx21
    image: ubuntu-22.04
    network:
      name: eth2-prater
      ip_range: 10.10.0.0/24
      ip: 10.10.0.25
  - name: "update-stereum--full--ubuntu-2004"
    server_type: cpx21
    image: ubuntu-20.04
    network:
      name: eth2-prater
      ip_range: 10.10.0.0/24
      ip: 10.10.0.26
#  - name: "update-stereum--default--centos-stream-8"
#    server_type: cx21
#    image: centos-stream-8
provisioner:
  name: ansible
  config_options:
    ssh_connection:
      ssh_args: -o ServerAliveInterval=30 -o ControlMaster=auto -o ControlPersist=60s
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    #- idempotence
    - lint
    - verify
    - destroy