---
- name: Prepare
  hosts: all
  tasks:
    - name: Make sure Stereum's config path exists
      file:
        path: "/etc/stereum/services"
        state: directory
        owner: "root"
        group: "root"
        mode: 0644
      become: yes

    - name: Create Prometheus service config
      copy:
        dest: "/etc/stereum/services/b6d8373f-2819-45d2-a923-57842f163a9b.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: PrometheusService
          id: b6d8373f-2819-45d2-a923-57842f163a9b
          configVersion: 1
          command: sh -c "/bin/prometheus --config.file=/etc/prometheus/prometheus.yml
            --web.enable-lifecycle"
          entrypoint: []
          env: {}
          image: prom/prometheus:v2.41.0
          ports:
            - 127.0.0.1:9090:9090/tcp
          volumes:
            - /opt/stereum/prometheus-b6d8373f-2819-45d2-a923-57842f163a9b/data/prometheus:/prometheus
            - /opt/stereum/prometheus-b6d8373f-2819-45d2-a923-57842f163a9b/config:/etc/prometheus
          user: "2000"
          autoupdate: true
          network: goerli
          dependencies:
            executionClients: []
            consensusClients: []
            mevboost: []
      become: yes

    - name: Create Geth service config
      copy:
        dest: "/etc/stereum/services/f47c3e8f-1f0d-96c8-02a0-c5136edfe256.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: GethService
          id: f47c3e8f-1f0d-96c8-02a0-c5136edfe256
          configVersion: 1
          command:
            - --goerli
            - --datadir=/opt/data/geth
            - --http
            - --http.port=8545
            - --http.addr=0.0.0.0
            - --http.vhosts=*
            - --http.api="engine,eth,web3,net,debug"
            - --http.corsdomain=*
            - --ws
            - --ws.port=8546
            - --ws.addr=0.0.0.0
            - --ws.api="debug,eth,net,web3"
            - --ws.origins=*
            - --authrpc.port=8551
            - --authrpc.addr=0.0.0.0
            - --authrpc.vhosts=*
            - --authrpc.jwtsecret=/engine.jwt
            - --metrics
            - --metrics.expensive
            - --metrics.port=6060
            - --metrics.addr=0.0.0.0
          entrypoint:
            - geth
          env: {}
          image: ethereum/client-go:v1.11.6
          ports:
            - 0.0.0.0:30303:30303/tcp
            - 0.0.0.0:30303:30303/udp
            - 127.0.0.1:8545:8545/tcp
          volumes:
            - /opt/stereum/geth-f47c3e8f-1f0d-96c8-02a0-c5136edfe256/data:/opt/data/geth
            - /opt/stereum/geth-f47c3e8f-1f0d-96c8-02a0-c5136edfe256/engine.jwt:/engine.jwt
          user: root
          autoupdate: true
          network: goerli
          dependencies:
            executionClients: []
            consensusClients: []
            mevboost: []
      become: yes

    - name: Create Besu service config
      copy:
        dest: "/etc/stereum/services/709d71ea-f75c-efc4-39f6-382f8b4fbbf5.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: BesuService
          id: 709d71ea-f75c-efc4-39f6-382f8b4fbbf5
          configVersion: 1
          command:
            - --network=goerli
            - --data-path=/opt/app/data
            - --data-storage-format=BONSAI
            - --pruning-enabled=true
            - --sync-mode=X_SNAP
            - --p2p-port=30303
            - --p2p-host=0.0.0.0
            - --rpc-http-enabled=true
            - --rpc-http-host=0.0.0.0
            - --rpc-http-cors-origins=*
            - --rpc-http-port=8545
            - --rpc-ws-enabled=true
            - --rpc-ws-host=0.0.0.0
            - --rpc-ws-port=8546
            - --host-allowlist=*
            - --metrics-enabled
            - --metrics-host=0.0.0.0
            - --metrics-port=9545
            - --logging=INFO
            - --engine-rpc-enabled=true
            - --engine-host-allowlist=*
            - --engine-rpc-port=8551
            - --engine-jwt-enabled=true
            - --engine-jwt-secret=/engine.jwt
          entrypoint:
            - besu
          env:
            JAVA_OPTS: -Xmx4g
          image: hyperledger/besu:23.4.0
          ports:
            - 0.0.0.0:30303:30303/tcp
            - 0.0.0.0:30303:30303/udp
            - 127.0.0.1:8545:8545/tcp
            - 127.0.0.1:5000:8546/tcp
          volumes:
            - /opt/stereum/besu-709d71ea-f75c-efc4-39f6-382f8b4fbbf5/data:/opt/app/data
            - /opt/stereum/besu-709d71ea-f75c-efc4-39f6-382f8b4fbbf5/engine.jwt:/engine.jwt
          user: "2000"
          autoupdate: true
          network: goerli
          dependencies:
            executionClients: []
            consensusClients: []
            mevboost: []
      become: yes

    - name: Create Nethermind service config
      copy:
        dest: "/etc/stereum/services/1d5a0a1b-feff-a954-77e8-9a19adef072c.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: NethermindService
          id: 1d5a0a1b-feff-a954-77e8-9a19adef072c
          configVersion: 1
          command:
            - --config=goerli
            - --log=info
            - --datadir=/opt/app/data
            - --Network.DiscoveryPort=30303
            - --Network.P2PPort=30303
            - --Merge.Enabled=true
            - --JsonRpc.Enabled=true
            - --JsonRpc.JwtSecretFile=/engine.jwt
            - --JsonRpc.Host=0.0.0.0
            - --JsonRpc.EngineHost=0.0.0.0
            - --Init.WebSocketsEnabled=true
            - --JsonRpc.WebSocketsPort=8546
            - --JsonRpc.EnabledModules=[web3,eth,subscribe,net]
            - --JsonRpc.AdditionalRpcUrls=http://0.0.0.0:8551|http;ws|engine;eth;subscribe
            - --Metrics.Enabled=true
            - --Metrics.ExposePort=6060
            - --HealthChecks.Enabled=true
            - --Pruning.Mode=Hybrid
          entrypoint:
            - ./Nethermind.Runner
          env: {}
          image: nethermind/nethermind:1.18.0
          ports:
            - 0.0.0.0:30303:30303/tcp
            - 0.0.0.0:30303:30303/udp
            - 127.0.0.1:8545:8545/tcp
            - 0.0.0.0:8546:8546/tcp
          volumes:
            - /opt/stereum/nethermind-1d5a0a1b-feff-a954-77e8-9a19adef072c/data:/opt/app/data
            - /opt/stereum/nethermind-1d5a0a1b-feff-a954-77e8-9a19adef072c/engine.jwt:/engine.jwt
          user: root
          autoupdate: true
          network: goerli
          dependencies:
            executionClients: []
            consensusClients: []
            mevboost: []
      become: yes

    - name: Create Erigon service config
      copy:
        dest: "/etc/stereum/services/6b0416ae-de58-7c12-ecc7-e7cc2cef4bc4.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: ErigonService
          id: 6b0416ae-de58-7c12-ecc7-e7cc2cef4bc4
          configVersion: 1
          command:
            - erigon
            - --chain=goerli
            - --datadir=/opt/data/erigon
            - --authrpc.addr=0.0.0.0
            - --authrpc.vhosts=*
            - --authrpc.port=8551
            - --authrpc.jwtsecret=/engine.jwt
            - --prune=htc
            - --externalcl
            - --ws
            - --http
            - --http.vhosts=*
            - --http.corsdomain=*
            - --http.addr=0.0.0.0
            - --http.port=8545
            - --http.api=engine,net,eth,web3
            - --metrics
            - --metrics.addr=0.0.0.0
            - --metrics.port=6060
          entrypoint: []
          env: {}
          image: thorax/erigon:v2.42.0
          ports:
            - 0.0.0.0:30303:30303/tcp
            - 0.0.0.0:30303:30303/udp
            - 127.0.0.1:8545:8545/tcp
          volumes:
            - /opt/stereum/erigon-6b0416ae-de58-7c12-ecc7-e7cc2cef4bc4/data:/opt/data/erigon
            - /opt/stereum/erigon-6b0416ae-de58-7c12-ecc7-e7cc2cef4bc4/engine.jwt:/engine.jwt
          user: root
          autoupdate: true
          network: goerli
          dependencies:
            executionClients: []
            consensusClients: []
            mevboost: []
      become: yes
# EOF
