---
- name: Prepare
  hosts: all
  tasks:
    - name: Install cron for Ansible (Ubuntu)
      apt:
        update_cache: yes
        name: cron
        state: present
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y crontabs
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "CentOS"
