---
dependency:
  name: galaxy
driver:
  name: hetznercloud
platforms:
  - name: "validator-import-lighthouse--default--ubuntu-22.04"
    hostname: ubuntu
    server_type: cpx21
    image: ubuntu-22.04
#  - name: "validator-import-lighthouse--default--centos-stream-8"
#    hostname: "centos"
#    server_type: cpx21
#    image: centos-stream-8
provisioner:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    #- idempotence
    - lint
    - verify
    - destroy
