---
- name: Check if there is a CharonService
  find:
    paths: "/etc/stereum/services"
    read_whole_file: true
    contains: "^\s*service:\s*CharonService"
  register: charon_service_files

- name: Set CharonService id
  set_fact:
    charon_service_id: "{{ charon_service_files.files[0].path | basename | split('.') | first }}"
  when: charon_service_files.matched > 0

- debug:
    var: charon_service_id
  when: charon_service_files.matched > 0

- name: Find service configs which contain CharonService ID
  find:
    paths: "/etc/stereum/services"
    read_whole_file: true
    contains: "{{ charon_service_id }}"
  register: service_config_files
  when: charon_service_files.matched > 0

- debug:
    var: service_config_files
  when: charon_service_files.matched > 0

- name: Include SDVT Changes
  include_tasks: sdvt_changes.yaml
  loop: "{{ service_config_files.files }}"
  when: charon_service_files.matched > 0
