---
- name: Install ufw, fail2ban
  apt:
    name:
      - ufw
      - fail2ban
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Install ufw, fail2ban
  yum:
    name:
      - ufw
      - fail2ban
    state: present
  when: ansible_facts['distribution'] == "CentOS"
# EOF
