---
- name: read ssh ports
  shell: /usr/sbin/sshd -T|awk '/^port|listenaddress\s/ {num = split($2, arr, ":"); print arr[num]}'|sort -u
  register: ssh_ports_config

- name: set fact ssh ports
  set_fact:
    common_ssh_ports: "{{ ssh_ports_config.stdout_lines }}"
  when: ssh_ports_config.stdout_lines | length > 0

- name: set fact ssh ports
  set_fact:
    common_ssh_ports:
      - "22"
  when: ssh_ports_config.stdout | length == 0

- name: Firewall enable & deny incoming
  ufw:
    state: enabled
    direction: incoming
    policy: deny
  environment:
    PATH: /sbin:{{ ansible_facts['env'].PATH }}

- name: Firewall allow ssh ports
  ufw:
    direction: in
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items: "{{ common_ssh_ports }}"
  environment:
    PATH: /sbin:{{ ansible_facts['env'].PATH }}
# EOF
