---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    prometheus_service: 4e647253-8c7c-4d79-a0c3-1e670f2b6638
    geth_service: 12ac7669-1874-426a-aae7-65c381ed1ec8
    grafana_service: 0af126fa-c881-456f-9388-e977fb1537bf
    grafana_provisioning: ["geth"]

  tasks:
    # prometheus service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ prometheus_service }}"
              image: "prom/prometheus:{{ stereum_static.defaults.versions.prometheus }}"
              ports:
                - 127.0.0.1:9090:9090/tcp
              env:
                CONFIG: |
                  global:
                    scrape_interval:     15s
                    evaluation_interval: 15s

                  scrape_configs:
                    - job_name: 'stereum-{{ geth_service }}'
                      metrics_path: /debug/metrics/prometheus
                      static_configs:
                        - targets: ['stereum-{{ geth_service }}:6060']
              command: sh -c "touch /etc/prometheus/prometheus.yml &&
                              echo \"$CONFIG\" > /etc/prometheus/prometheus.yml &&
                              /bin/prometheus --config.file=/etc/prometheus/prometheus.yml"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ prometheus_service }}/data/prometheus:/prometheus"
                - "/opt/app/services/{{ prometheus_service }}/config:/etc/prometheus"
    # grafana service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ grafana_service }}"
              image: "grafana/grafana:{{ stereum_static.defaults.versions.grafana }}"
              ports:
                - 127.0.0.1:3000:3000/tcp
              env:
                GRAFANA_INI: |
                  [auth.anonymous]
                  enabled = true
                  org_role = Admin
              command: bash -c "touch /etc/grafana/grafana.ini &&
                                echo \"$GRAFANA_INI\" > /etc/grafana/grafana.ini &&
                                /run.sh"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ grafana_service }}/grafana/provisioning:/etc/grafana/provisioning"
                - "/opt/app/services/{{ grafana_service }}/grafana/data:/var/lib/grafana"
                - "/opt/app/services/{{ grafana_service }}/grafana:/etc/grafana"

    # replace prometheus service-id into grafana's datasource.yml
    - name: replace prometheus-ID into grafana's datasource.yml
      replace:
        path: "/opt/app/services/{{ grafana_service }}/grafana/provisioning/datasources/datasource.yml"
        regexp: '  url: http:\/\/prometheus:9090'
        replace: '  url: http://stereum-{{ prometheus_service }}:9090'
      become: yes
