---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    teku_service: 0c851526-1fe8-11ed-a4bc-a304c2a39bd6
    nethermind_service: 0cb6869c-1fe8-11ed-a431-a752cb022fb5
    mevboost_service: 0ce6b4ac-1fe8-11ed-b9c2-bb5736e3d599

  tasks:
    # nethermind service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: NethermindService
              id: "{{ nethermind_service }}"
              image: "nethermind/nethermind:{{ stereum_static.defaults.versions.nethermind }}"
              ports:
                - 0.0.0.0:30303:30303/tcp
                - 0.0.0.0:30303:30303/udp
              entrypoint: ["./Nethermind.Runner"]
              env: {}
              command:
              - --config=goerli
              - --datadir=/opt/app/data
              - --Merge.Enabled=true
              - --JsonRpc.JwtSecretFile=/engine.jwt
              - --JsonRpc.EngineHost=0.0.0.0
              - --JsonRpc.EnginePort=8551
              user: "root"
              volumes:
                - "/opt/app/services/{{ nethermind_service }}/data:/opt/app/data"
                - "/opt/app/services/{{ nethermind_service }}/engine.jwt:/engine.jwt"

    # teku beacon & validator service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"

      - name: "Include manage-service"
        include_role:
          name: "manage-service"

      - name: Create keystore password
        copy:
          content: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"
          dest: /opt/app/services/{{ teku_service }}/data/teku_api_password.txt
          force: no
        become: yes

      - name: Get teku-api password
        slurp:
          src: "/opt/app/services/{{ teku_service }}/data/teku_api_password.txt"
        register: teku_api_password
        become: yes

      - name: Set variable
        set_fact:
          api_password: "{{ teku_api_password.content | b64decode | trim }}"

      - name: Create keystore file
        command: bash -c "keytool -genkeypair
                          -keystore teku_api_keystore
                          -storetype PKCS12
                          -storepass '{{ api_password }}'
                          -keyalg RSA
                          -keysize 2048
                          -validity 109500
                          -dname 'CN=localhost, OU=MyCompanyUnit, O=MyCompany, L=MyCity, ST=MyState, C=AU'
                          -ext san=dns:localhost,ip:127.0.0.1"
        args:
          chdir: /opt/app/services/{{ teku_service }}/data
        changed_when: false
        become: yes

      - name: Waiting for the services to start properly
        pause:
          seconds: 15

      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: TekuBeaconValidatorService
              id: "{{ teku_service }}"
              image: "consensys/teku:{{ stereum_static.defaults.versions.teku }}"
              ports:
                - 0.0.0.0:9001:9001/tcp
                - 0.0.0.0:9001:9001/udp
              env:
                JAVA_OPTS: -Xmx4g
              entrypoint: ["/opt/teku/bin/teku"]
              command:
                - --network=prater
                - --data-path=/opt/app/data
                - --ee-endpoint=http://stereum-{{ nethermind_service }}:8551
                - --ee-jwt-secret-file=/engine.jwt
                - --validators-builder-registration-default-enabled=true
                - --validators-proposer-blinded-blocks-enabled=true
                - --validators-proposer-default-fee-recipient=0x5dC29815e46dfb5EAb5C57606f8e2A5FbBdb454e
                - --builder-endpoint=http://stereum-{{ mevboost_service }}:18550
              user: "2000"
              volumes:
                - "/opt/app/services/{{ teku_service }}/data:/opt/app/data"
                - "/opt/app/services/{{ nethermind_service }}/engine.jwt:/engine.jwt"

    # mevboost service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: MevBoostService
              id: "{{ mevboost_service }}"
              image: flashbots/mev-boost:{{ stereum_static.defaults.versions.mevboost }}
              env: {}
              ports: []
              command: []
              entrypoint:
                - /app/mev-boost
                - -addr
                - 0.0.0.0:18550
                - -goerli
                - -relay-check
                - -relays
                - "{{ stereum_static.defaults.relay.goerli }}"
              user: "2000"
              volumes: []

# EOF