---
- name: Prepare
  hosts: all
  roles:
    - role: '../'
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml
  vars:
    beacon_service: 731c4b72-7f7c-11ec-b824-c304f53cda24
    ssv_service: f6a89270-7fa4-11ec-9378-fbd364d02350
    ssv_config: |
      eth2:
        Network: "prater"
        BeaconNodeAddr: "http://stereum-{{ beacon_service }}:5051"
      eth1:
        ETH1Addr: "ws://10.10.0.2:8545"
        RegistryContractAddr: "0x687fb596F3892904F879118e2113e1EEe8746C2E"
      OperatorPrivateKey: ""
      global:
        LogLevel: "debug"
      MetricsAPIPort: 15000

  tasks:
    - name: Install python for Ansible (Ubuntu)
      raw: apt update && apt install -y pip
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - include_role:
        name: "setup"

    - include_role:
        name: "configure-firewall"

    - name: Create SSV config file
      file:
        path: "/opt/app/services/{{ ssv_service }}/data/blox/ssv"
        state: directory
        recurse: yes
        owner: "2000"
        group: "2000"
      become: yes

    - name: Write SSV configuration
      ansible.builtin.copy:
        content: "{{ ssv_config }}"
        dest: "/opt/app/services/{{ ssv_service }}/data/blox/ssv/config.yaml"
        owner: "2000"
        group: "2000"
        mode: 0644
      become: yes

    - block:
      - name: Set fastsync params
        set_fact:
          stereum:
            fastsync:
              network: prater
              service: teku
              dest: /opt/app/services/{{ beacon_service }}/data
      - include_role:
          name: "fastsync"

    # teku beacon & validator service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ beacon_service }}"
              image: consensys/teku:21.12.2
              ports:
                - 0.0.0.0:9001:9001/tcp
                - 0.0.0.0:9001:9001/udp
              env:
                JAVA_OPTS: -Xmx3g
              entrypoint: []
              command: |
                /opt/teku/bin/teku
                --network=prater
                --p2p-enabled=true
                --p2p-port=9001
                --eth1-endpoint=http://10.10.0.3:8545
                --metrics-enabled=true
                --metrics-categories=BEACON,LIBP2P,NETWORK,PROCESS
                --metrics-port=8008
                --metrics-interface=0.0.0.0
                --metrics-host-allowlist="*"
                --data-path=/opt/app/data
                --data-storage-mode=archive
                --rest-api-port=5051
                --rest-api-host-allowlist="*"
                --rest-api-interface=0.0.0.0
                --rest-api-docs-enabled=true
                --rest-api-enabled=true
                --log-destination=CONSOLE
              user: "2000"
              volumes:
                - "/opt/app/services/{{ beacon_service }}/data/teku:/opt/app/data"
