---
- name: Docker on CentOS
  include_tasks: docker-centos.yaml
  when: ansible_facts['distribution'] == "CentOS"

- name: Docker on Ubuntu
  include_tasks: docker-ubuntu.yaml
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- name: Enable service docker
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started
