---
- name: Apply stereum configuration to this setup
  set_fact:
    stereum: "{{ stereum_static }}"
  when: stereum is undefined

- include_tasks: update-os-ubuntu.yml
  when: ansible_facts['distribution'] == 'Debian' or ansible_facts['distribution'] == 'Ubuntu'

- include_tasks: update-os-centos.yml
  when: ansible_facts['distribution'] == "CentOS"

- include_tasks: timesyncd.yml

- include_tasks: docker.yml

- include_tasks: zip-centos.yml
  when: ansible_facts['distribution'] == "CentOS"

- include_tasks: stereum-config.yml
