---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - stat: path=/etc/stereum/services
    register: stereum_services_dir
  - debug:
      msg: "{{ stereum_services_dir }}"
  # ufw
  - shell: ufw status
    register: stereum_ufw_status
  - debug:
      msg: "{{ stereum_ufw_status }}"
  - assert:
      that:
      - stereum_ufw_status.stdout.find("12000/udp") != -1
      - stereum_ufw_status.stdout.find("13000/tcp") != -1
      - stereum_ufw_status.stdout.find("12001/udp") != -1
      - stereum_ufw_status.stdout.find("13001/tcp") != -1
  # ssv config file
  - stat: path=/opt/app/services/99e8942a-82e9-11ec-9f76-cbc103131365/data/blox/ssv/config.yaml
    register: ssv_config_file
  - debug:
      msg: "{{ ssv_config_file }}"
  - name: Check for ssv config
    assert:
      that:
        - ssv_config_file.stat.exists
  - name: Waiting for the services to start properly
    pause:
      minutes: 10
  # prysm beacon & ssv logs
  - name: prysm beacon node
    command: "docker logs --tail=150 stereum-995c224c-82e9-11ec-9115-2349bc4566fa"
    register: beacon
    until: beacon.stderr is not search('estimated time remaining')
    retries: 360
    delay: 10
  - name: Blox-SSV
    command: "docker logs --tail=250 stereum-99e8942a-82e9-11ec-9f76-cbc103131365"
    register: blox_ssv
    until: 
      - blox_ssv.stderr.find("beacon node is not healthy") == -1
      - blox_ssv.stderr.find("at peer limit") != -1
    retries: 360
    delay: 10
  # container's images & ports
  - shell: docker ps
    register: stereum_docker_ps
  - debug:
      msg: "{{ stereum_docker_ps }}"
  - assert:
      that:
      - stereum_docker_ps.stdout.find("gcr.io/prysmaticlabs/prysm/beacon-chain") != -1
      - stereum_docker_ps.stdout.find("bloxstaking/ssv-node") != -1
      - stereum_docker_ps.stdout.find("4000->4000") != -1
      - stereum_docker_ps.stdout.find("12000->12000") != -1
      - stereum_docker_ps.stdout.find("13000->13000") != -1
      - stereum_docker_ps.stdout.find("12001->12001") != -1
      - stereum_docker_ps.stdout.find("13001->13001") != -1
      - (stereum_docker_ps.stdout|regex_findall("Up")|length) == 2  
