---
- name: Find service configs
  find:
    paths: "/etc/stereum/services"
  register: service_config_files

- name: Include Teku Changes
  include_tasks: teku_changes.yaml
  loop: "{{ service_config_files.files }}"
  loop_control:
    loop_var: config_file

- name: Include Geth Changes
  include_tasks: geth_changes.yaml
  loop: "{{ service_config_files.files }}"
  loop_control:
    loop_var: config_file
