---
- name: Prepare
  hosts: all
  tasks:
    - name: Update cache & os (Ubuntu)
      apt:
        update_cache: yes
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "Ubuntu"

    # - name: Install python for Ansible (CentOS 8)
    #   raw: yum install -y crontabs
    #   become: true
    #   changed_when: false
    #   when: ansible_facts['distribution'] == "CentOS"
