---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    prometheus_service: f52b6dcc-e0d5-11ec-8e8d-87f977a4cd88
    prometheus_node_exporter_service: ffd332e6-e0d5-11ec-a82b-9b01f3fb02d7
    grafana_service: 0ee5a0e8-e0d6-11ec-add4-3b3d662c25b1
    beacon_service: 1929168e-e0d6-11ec-9183-97daacc21ea6
    grafana_provisioning: teku

  tasks:
    # prometheus service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ prometheus_service }}"
              image: "prom/prometheus:{{ stereum.defaults.versions.prometheus }}"
              ports:
                - 127.0.0.1:9090:9090/tcp
              env:
                CONFIG: |
                  global:
                    scrape_interval:     15s
                    evaluation_interval: 15s

                  alerting:
                    alertmanagers:
                    - static_configs:
                      - targets:
                        # - alertmanager:9093

                  rule_files:
                    # - "first_rules.yml"
                    # - "second_rules.yml"

                  scrape_configs:
                    - job_name: 'stereum-{{ beacon_service }}'
                      static_configs:
                        - targets: ['stereum-{{ beacon_service }}:5054']
                    - job_name: 'stereum-{{ prometheus_node_exporter_service }}'
                      static_configs:
                        - targets: ['stereum-{{ prometheus_node_exporter_service }}:9100']
              command: sh -c "touch /etc/prometheus/prometheus.yml &&
                              echo \"$CONFIG\" > /etc/prometheus/prometheus.yml &&
                              /bin/prometheus --config.file=/etc/prometheus/prometheus.yml"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ prometheus_service }}/data/prometheus:/prometheus"
                - "/opt/app/services/{{ prometheus_service }}/config:/etc/prometheus"
    # prometheus node-exporter service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ prometheus_node_exporter_service }}"
              image: "prom/node-exporter:{{ stereum.defaults.versions.node_exporter }}"
              ports: []
              env: {}
              command: []
              entrypoint: ["/bin/node_exporter"]
              user: "2000"
              volumes: []
    # grafana service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ grafana_service }}"
              image: "grafana/grafana:{{ stereum.defaults.versions.grafana }}"
              ports:
                - 127.0.0.1:3000:3000/tcp
              env:
                GRAFANA_INI: |
                  [auth.anonymous]
                  enabled = true
                  org_role = Admin
                GRAFANA_PROVISIONING: "{{ grafana_provisioning }}"
              command: bash -c "touch /etc/grafana/grafana.ini &&
                                echo \"$GRAFANA_INI\" > /etc/grafana/grafana.ini &&
                                /run.sh"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ grafana_service }}/grafana/provisioning:/etc/grafana/provisioning"
                - "/opt/app/services/{{ grafana_service }}/grafana/data:/var/lib/grafana"
                - "/opt/app/services/{{ grafana_service }}/grafana:/etc/grafana"
