blank_issues_enabled: true
contact_links:
  - name: ğŸŒ Stereum Website
    url: https://stereum.net/
    about: "Get more information about Stereum!"
  - name: ğŸ“š Stereum Documentation
    url: https://stereum-dev.github.io/ethereum-node-web-docs/
    about: "Check out our Documentation!"
  - name: ğŸ’¬ Stereum Discord Channel
    url: https://discord.gg/UPVKtw6Wte
    about: "If you need more support, please visit our Discord!"
  - name: ğŸ“„ Documentation Feedback
    url: https://github.com/stereum-dev/ethereum-node-web-docs/issues/new/choose
    about: "Suggest improvements or report issues with our documentation."

issue_templates:
  - name: ğŸª³ Bug Report
    about: Report a bug to help us improve. Describe the issue in detail, including steps to reproduce if possible.
    template: bug_report.md
    labels: ["bug"]
  - name: ğŸ„ Enhancement Request
    about: Suggest a new feature or improvement. Describe the enhancement and its potential benefits.
    template: enhancement_request.md
    labels: ["enhancement"]
  - name: ğŸ”Œ Service Integration
    about: Propose a new service integration. Describe the service, how it integrates, and the value it adds to the project.
    template: service_integration.md
    labels: ["integration"]
