blank_issues_enabled: true
contact_links:
  - name: ğŸŒ Stereum Website
    url: https://stereum.net/
    about: "Get more information about Stereum!"
  - name: ğŸ“š Stereum Documentation
    url: https://stereum-dev.github.io/ethereum-node-web-docs/
    about: "Check out our Documentation!"
  - name: ğŸ’¬ Stereum Discord Channel
    url: https://discord.gg/UPVKtw6Wte
    about: "If you need more support, please visit our Discord!"
  - name: ğŸ“„ Documentation Feedback
    url: https://github.com/stereum-dev/ethereum-node-web-docs/issues/new/choose
    about: "Suggest improvements or report issues with our documentation."

issue_templates:
  - name: ğŸª³ Bug Report
    about: Report a bug to help us improve. Describe the issue in detail, including steps to reproduce if possible.
    file: "bug_report.yml"
    labels: ["bug"]
  - name: ğŸ„ Enhancement Request
    about: Suggest a new feature or improvement. Describe the enhancement and its potential benefits.
    file: "enhancement_request.yml"
    labels: ["enhancement"]
  - name: ğŸ”Œ Service Integration
    about: Propose a new service integration. Describe the service, how it integrates, and the value it adds to the project.
    file: "service_integration.yml"
    labels: ["integration"]
  - name: "ğŸ› ï¸ Refactor"
    description: "Propose a refactor to the existing codebase."
    labels: ["refactor"]
    file: "refactor.yml"
  - name: ğŸ¤– Automated Testing Improvement
    about: Suggest an enhancement or report an issue related to automated testing.
    file: "automated_testing.yml"
    labels: ["enhancement", "automated testing"]
