---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    nethermind_service: 2863e820-231d-11ed-98f1-cf0e0c718b2b
    nimbus_service: 28bf6a92-231d-11ed-ae9e-c75fab7a77b6
    mevboost_service: 28eefbc2-231d-11ed-80f7-0b2dcd8ce871

  tasks:
    # nethermind service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: NethermindService
              id: "{{ nethermind_service }}"
              image: "nethermind/nethermind:{{ stereum_static.defaults.versions.nethermind }}"
              ports:
                - 0.0.0.0:30303:30303/tcp
                - 0.0.0.0:30303:30303/udp
              entrypoint: ["./Nethermind.Runner"]
              env: {}
              command:
              - --config=goerli
              - --datadir=/opt/app/data
              - --Merge.Enabled=true
              - --JsonRpc.JwtSecretFile=/engine.jwt
              - --JsonRpc.EngineHost=0.0.0.0
              - --JsonRpc.EnginePort=8551
              user: "root"
              volumes:
                - "/opt/app/services/{{ nethermind_service }}/data:/opt/app/data"
                - "/opt/app/services/{{ nethermind_service }}/engine.jwt:/engine.jwt"

   # nimbus beacon & validator service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      - name: Create api-token file
        copy:
          content: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"
          dest: /opt/app/services/{{ nimbus_service }}/validator/api-token.txt
          force: no
        become: yes
      - name: Waiting for the services to start properly
        pause:
          seconds: 15
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: NimbusBeaconValidatorService
              id: "{{ nimbus_service }}"
              image: statusim/nimbus-eth2:{{ stereum_static.defaults.versions.nimbus }}
              ports:
                - 0.0.0.0:9000:9000/tcp
                - 0.0.0.0:9000:9000/udp
              env: {}
              entrypoint: ["/home/user/nimbus-eth2/build/nimbus_beacon_node"]
              command:
                - --network=goerli
                - --data-dir=/opt/app/beacon
                - --validators-dir=/opt/app/validators
                - --secrets-dir=/opt/app/secrets
                - --web3-url=http://stereum-{{ nethermind_service }}:8551
                - --tcp-port=9000
                - --udp-port=9000
                - --rest
                - --rest-address=0.0.0.0
                - --rest-port=5052
                - --jwt-secret=/engine.jwt
                - --suggested-fee-recipient=0x5dC29815e46dfb5EAb5C57606f8e2A5FbBdb454e
                - --keymanager
                - --keymanager-address=0.0.0.0
                - --keymanager-token-file=/opt/app/validators/api-token.txt
                - --payload-builder=true
                - --payload-builder-url=http://stereum-{{ mevboost_service }}:18550
              user: "2000"
              volumes:
                - "/opt/app/services/{{ nimbus_service }}/beacon:/opt/app/beacon"
                - "/opt/app/services/{{ nimbus_service }}/validator:/opt/app/validators"
                - "/opt/app/services/{{ nimbus_service }}/validator/secrets:/opt/app/secrets"
                - "/opt/app/services/{{ nethermind_service }}/engine.jwt:/engine.jwt"

    # mevboost service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: MevBoostService
              id: "{{ mevboost_service }}"
              image: flashbots/mev-boost:{{ stereum_static.defaults.versions.mevboost }}
              env: {}
              ports: []
              command: []
              entrypoint:
                - /app/mev-boost
                - -addr
                - 0.0.0.0:18550
                - -goerli
                - -relay-check
                - -relays
                - "{{ stereum_static.defaults.relay.goerli }}"
              user: "2000"
              volumes: []

# EOF