---
- name: Write API data
  template:
    src: "validator-fee-recipient-api-data.json"
    dest: "/tmp/validator-fee-recipient-api-data"
    owner: "2000"
    group: "2000"
    mode: 0600
  become: yes

- name: Validator fee recipient using API
  community.docker.docker_container:
    command_handling: correct
    name: "validator-fee-recipient-api-curl"
    user: "2000"
    image: "curlimages/curl:{{ stereum_static.defaults.versions.curl }}"
    detach: false
    command: |
      curl -X POST {{ api_service_protocol | default("http") }}://stereum-{{ validator_service }}:{{ validator_port }}/eth/v1/validator/{{ item.pubkeys }}/feerecipient
      -H "Content-Type: application/json"
      -H "Authorization: Bearer {{ api_token }}"
      -d "@/validator-fee-recipient-api-data"
      -s
    networks:
      - name: stereum
    volumes:
      - "/tmp/validator-fee-recipient-api-data:/validator-fee-recipient-api-data"
  become: yes
  register: validator_fee_recipient_api_result

- name: Log set fee recipient result
  debug:
    msg: "{{ validator_fee_recipient_api_result.container.Output }}"

- name: Remove API data file
  ansible.builtin.file:
    path: "/tmp/validator-fee-recipient-api-data"
    state: absent

- name: Remove docker container
  community.docker.docker_container:
    name: "validator-fee-recipient-api-curl"
    state: absent

# EOF
