# Stereum system settings
# prettier-ignore
stereum_settings:
  settings:
    controls_install_path: {{ stereum.settings.controls_install_path | default(stereum.defaults.controls_install_path) }}
    updates:
      lane: {{ stereum.settings.updates.lane | default(stereum.defaults.updates.lane) }}
      unattended:
        install: {{ stereum.settings.updates.unattended.install | default(stereum.defaults.updates.unattended.install) }}
