---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    beacon_service: 493f2578-7e13-11ec-80bb-1b593d9699ff
    ssv_service: 52d77bd0-7e13-11ec-a95e-bb669ccf3e66

  tasks:
    # ssv operator keys
    - block:
      - name: Generate SSV network keys
        command: bash -c "docker run -d --name=ssv_node_op_key -it 'bloxstaking/ssv-node:v0.1.10' /go/bin/ssvnode generate-operator-keys &&
                          docker logs ssv_node_op_key --follow &&
                          docker stop ssv_node_op_key &&
                          docker rm ssv_node_op_key"
        register: ssv_keys
        changed_when: false
        become: yes
      - name: Parse keys
        set_fact:
          ssv:
            enabled: true
            pk: "{{ ssv_keys.stdout | regex_search('(?<=\"pk\":\\s\").*(?=\")') }}"
            sk: "{{ ssv_keys.stdout | regex_search('(?<=\"sk\":\\s\").*(?=\")') }}"

    # ssv service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ ssv_service }}"
              image: bloxstaking/ssv-node:alpine-dns
              ports:
                - 0.0.0.0:12000:12000/udp
                - 0.0.0.0:13000:13000/tcp
              env:
                CONFIG_PATH: /data/config.yaml
                CONFIG: |
                  eth2:
                    Network: "prater"
                    BeaconNodeAddr: "http://stereum-{{ beacon_service }}:5052"
                  eth1:
                    ETH1Addr: "ws://10.10.0.2:8545"
                    RegistryContractAddr: "0x687fb596F3892904F879118e2113e1EEe8746C2E"
                  OperatorPrivateKey: "{{ ssv.sk }}"
                  global:
                    LogLevel: "debug"
                  MetricsAPIPort: 15000
              command: bash -c "touch /data/config.yaml &&
                                echo \"$CONFIG\" > /data/config.yaml &&
                                make BUILD_PATH=/go/bin/ssvnode start-node &&
                                docker logs ssv_node"
              entrypoint: []
              user: "2000"
              volumes:
                - "/opt/app/services/{{ ssv_service }}/data/blox/ssv:/data"
