---
- name: Prepare
  hosts: all
  roles:
    - role: "../"
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml
  vars:
    beacon_service: e3ae009e-e019-11ec-8d7a-a36ff73c89bf
    geth_service: 007af7fe-e01a-11ec-ab78-37ce2b265e8b

  tasks:
    - name: Install python for Ansible (Ubuntu)
      apt:
        update_cache: yes
        name: pip
        state: present
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_facts['distribution'] == "CentOS"

    - include_role:
        name: "setup"

    - include_role:
        name: "configure-firewall"

    - name: Write service configuration
      copy:
        dest: "/etc/stereum/services/{{ beacon_service }}.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          command:
            - lighthouse
            - bn
            - --debug-level=debug
            - --network=prater
            - --eth1-endpoints=http://stereum-"{{ geth_service }}":8545
            - --eth1-blocks-per-log-query=150
            - --datadir=/opt/app/beacon
            - --http
            - --http-address=0.0.0.0
            - --metrics
            - --metrics-address=0.0.0.0
            - --disable-upnp
            - --validator-monitor-auto
            - --slasher
            - --slasher-dir=/opt/app/slasher
            - --slasher-max-db-size=16
          entrypoint: []
          env: {}
          service: LighthouseBeaconService
          id: {{ beacon_service }}
          image: "sigp/lighthouse:{{ stereum_static.defaults.versions.lighthouse }}"
          ports:
            - 0.0.0.0:9000:9000/tcp
            - 0.0.0.0:9000:9000/udp
            - 127.0.0.1:5052:5052/tcp
          volumes:
            - "/opt/stereum/lighthouse/beacon:/opt/app/beacon"
            - "/opt/stereum/lighthouse/slasher:/opt/app/slasher"
          user: 2000
          network: prater
      become: yes

    - name: Write service configuration geth
      copy:
        dest: "/etc/stereum/services/{{ geth_service }}.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          command: "geth --goerli --http --http.port=8545 --http.addr=0.0.0.0 --http.vhosts='*' --allow-insecure-unlock --http.api='db,eth,net,web3,personal'"
          entrypoint: []
          env:
            STEREUM_DUMMY: foobar
          service: GethService
          id: {{ geth_service }}
          image: "ethereum/client-go:{{ stereum_static.defaults.versions.geth }}"
          name: geth
          ports:
          - 0.0.0.0:30303:30303/tcp
          - 0.0.0.0:30303:30303/udp
          volumes:
          - /opt/stereum/geth:/root/.ethereum
          user: root
          network: goerli
      become: yes
