---
- name: Prepare
  hosts: all
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml
  vars:
    eth1_node: https://goerli.infura.io/v3/20fd3ed2418742e9b727857e32b40f9c
    validator_service: 2e83d610-48b8-11ec-802a-330dee8e6b2e
    beacon_service: e1370b42-5678-11ec-988b-5b5038492927  

  tasks:
    - name: Install python for Ansible (Ubuntu)
      raw: apt update && apt install -y pip
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Install pip, expect (Ubuntu)
      apt:
        update_cache: yes
        name:
          - python3-pip
          - expect
      become: true    
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install pip, expect (CentOS 8)
      yum:
        name:
          - python3-pip
          - expect
        state: latest
      become: true  
      when: ansible_distribution == "CentOS"  

    - include_role:
        name: "setup"

    # lh beacon service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: start
            configuration:
              id: "{{ beacon_service }}"
              image: stereum/lighthouse:v2.0.1-48
              hostname: "stereum-{{ beacon_service }}"
              env:
                DEBUG_LEVEL: debug
                NETWORK: prater
                ETH1_NODES: "{{ eth1_node }}"
                DATADIR: /opt/app/beacon
                SLASHERDIR: /opt/app/slasher
                SLASHER_DB_SIZE: "16"
              ports:
                - 0.0.0.0:9000:9000/tcp
                - 0.0.0.0:9000:9000/udp 
                - 127.0.0.1:5052:5052  
              command: []
              entrypoint: ["/opt/app/start/beacon.sh"]
              user: "2000"
              volumes:
                - "/opt/app/services/{{ beacon_service }}/beacon:/opt/app/beacon"
                - "/opt/app/services/{{ beacon_service }}/slasher:/opt/app/slasher"    

    # lh validator service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: start
            configuration:
              id: "{{ validator_service }}"
              image: stereum/lighthouse:v2.0.1-48
              hostname: "stereum-{{ validator_service }}"
              env:
                DEBUG_LEVEL: info
                NETWORK: prater
                DATADIR: /opt/app/validator
                LAUNCHPADDIR: /opt/app/launchpad
                GRAFFITI: stereum.net
                BEACON_NODES: "http://stereum-{{ beacon_service }}:5052"
              ports: []    
              command: []
              entrypoint: ["/opt/app/start/validator-stereum2.sh"]
              user: "2000"
              volumes:
                - "/opt/app/services/{{ validator_service }}/validator:/opt/app/validator"
                - "/opt/app/services/{{ validator_service }}/launchpad:/opt/app/launchpad"
                - /opt/app/import:/opt/app/import
