---
- name: Prepare
  hosts: all
  vars_files:
    - ../../../../defaults/stereum_defaults.yaml
  vars:
    consClient: "nimbus"
    beacon_service: 96d0bd64-b40b-11ec-9748-ef3d97c5f568

  tasks:
    - name: Install python for Ansible (Ubuntu)
      raw: apt update && apt install -y pip
      become: true
      changed_when: false
      when: ansible_distribution == "Ubuntu"

    - name: Install python for Ansible (CentOS 8)
      raw: yum install -y python38 tar && yum remove -y python36
      become: true
      changed_when: false
      when: ansible_distribution == "CentOS"

    - name: Install pip, expect (Ubuntu)
      apt:
        update_cache: yes
        name:
          - python3-pip
          - expect
      become: true
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

    - name: Install pip, expect (CentOS 8)
      yum:
        name:
          - python3-pip
          - expect
        state: latest
      become: true
      when: ansible_distribution == "CentOS"

    - include_role:
        name: "setup"

    - include_role:
        name: "configure-firewall"

    # nimbus beacon & validator service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      - name: Create api-token file
        copy:
          content: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"
          dest: /opt/app/services/{{ beacon_service }}/validator/validators/api-token.txt
          force: no
        become: yes
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              id: "{{ beacon_service }}"
              image: statusim/nimbus-eth2:multiarch-v22.3.0
              ports:
                - 0.0.0.0:9000:9000/tcp
                - 0.0.0.0:9000:9000/udp
                - 127.0.0.1:9190:9190/tcp
                - 127.0.0.1:5052:5052/tcp
              env: {}
              entrypoint: ["/home/user/nimbus-eth2/build/nimbus_beacon_node"]
              command:
                - --network=prater
                - --data-dir=/opt/app/beacon
                - --validators-dir=/opt/app/validators
                - --secrets-dir=/opt/app/secrets
                - --web3-url=ws://10.10.0.2:8545
                - --tcp-port=9000
                - --udp-port=9000
                - --rpc
                - --rpc-port=9190
                - --rpc-address=0.0.0.0
                - --metrics
                - --metrics-port=8008
                - --metrics-address=0.0.0.0
                - --rest
                - --rest-address=0.0.0.0
                - --rest-port=5052
                - --graffiti="stereum.net"
                - --keymanager
                - --keymanager-address=0.0.0.0
                - --keymanager-token-file=/opt/app/validators/api-token.txt
              user: "2000"
              volumes:
                - "/opt/app/services/{{ beacon_service }}/beacon:/opt/app/beacon"
                - "/opt/app/services/{{ beacon_service }}/validator/validators:/opt/app/validators"
                - "/opt/app/services/{{ beacon_service }}/validator/secrets:/opt/app/secrets"
