---
- name: Prepare
  hosts: all
  tasks:
    - name: Make sure Stereum's config path exists
      file:
        path: "/etc/stereum/services"
        state: directory
        owner: "root"
        group: "root"
        mode: 0644
      become: yes

    - name: Create ValidatorEjectorService config
      copy:
        dest: "/etc/stereum/services/15ce3684-4dbd-4657-8a21-b1243b72b1ca.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: ValidatorEjectorService
          id: 15ce3684-4dbd-4657-8a21-b1243b72b1ca
          configVersion: 1
          command: []
          entrypoint: []
          env:
            EXECUTION_NODE: http://stereum-ce456ae0-64d6-4886-a53b-6b90984d4913:8545
            CONSENSUS_NODE: http://stereum-e7bd77d1-4d20-4a2e-85a6-1915f105a4c6:5052
            LOCATOR_ADDRESS: "0x28FAB2059C713A7F9D8c86Db49f9bb0e96Af1ef8"
            STAKING_MODULE_ID: "123"
            OPERATOR_ID: "123"
            MESSAGES_LOCATION: /app/messages
            ORACLE_ADDRESSES_ALLOWLIST: '["0x140Bd8FbDc884f48dA7cb1c09bE8A2fAdfea776E",
              "0xA7410857ABbf75043d61ea54e07D57A6EB6EF186",
              "0x404335BcE530400a5814375E7Ec1FB55fAff3eA2",
              "0x946D3b081ed19173dC83Cd974fC69e1e760B7d78",
              "0x007DE4a5F7bc37E2F26c0cb2E8A95006EE9B89b5",
              "0xe57B3792aDCc5da47EF4fF588883F0ee0c9835C9",
              "0x61c91ECd902EB56e314bB2D5c5C07785444Ea1c8",
              "0x1Ca0fEC59b86F549e1F1184d97cb47794C8Af58d",
              "0xc79F702202E3A6B0B6310B537E786B9ACAA19BAf"]'
            HTTP_PORT: "8989"
            RUN_METRICS: "true"
            RUN_HEALTH_CHECK: "true"
            DRY_RUN: "false"
          image: lidofinance/validator-ejector:1.6.0
          ports: []
          volumes:
            - /opt/stereum/validatorejector-15ce3684-4dbd-4657-8a21-b1243b72b1ca/messages:/app/messages
          user: "2000"
          autoupdate: true
          network: mainnet
          dependencies:
            executionClients:
              - service: GethService
                id: ce456ae0-64d6-4886-a53b-6b90984d4913
            consensusClients:
              - service: LighthouseBeaconService
                id: e7bd77d1-4d20-4a2e-85a6-1915f105a4c6
            mevboost: []
            otherServices: []
      become: yes

    - name: Create ValidatorEjectorService config
      copy:
        dest: "/etc/stereum/services/41b15ea7-12d4-49f6-8448-8a6164edef36.yaml"
        owner: "root"
        group: "root"
        mode: 0644
        content: |
          service: ValidatorEjectorService
          id: 41b15ea7-12d4-49f6-8448-8a6164edef36
          configVersion: 1
          command: []
          entrypoint: []
          env:
            EXECUTION_NODE: http://stereum-cc1323ce-90a1-440f-8b78-f930a3300b38:8545
            CONSENSUS_NODE: http://stereum-62cb879b-b0f0-4ea2-bc13-f606b7f4cfb9:5052
            LOCATOR_ADDRESS: "0x28FAB2059C713A7F9D8c86Db49f9bb0e96Af1ef8"
            STAKING_MODULE_ID: "123"
            OPERATOR_ID: "123"
            MESSAGES_LOCATION: /app/messages
            ORACLE_ADDRESSES_ALLOWLIST: '["0x140Bd8FbDc884f48dA7cb1c09bE8A2fAdfea776E","0xA7410857ABbf75043d61ea54e07D57A6EB6EF186","0x404335BcE530400a5814375E7Ec1FB55fAff3eA2","0x946D3b081ed19173dC83Cd974fC69e1e760B7d78","0x007DE4a5F7bc37E2F26c0cb2E8A95006EE9B89b5","0xe57B3792aDCc5da47EF4fF588883F0ee0c9835C9","0x61c91ECd902EB56e314bB2D5c5C07785444Ea1c8","0x1Ca0fEC59b86F549e1F1184d97cb47794C8Af58d","0xc79F702202E3A6B0B6310B537E786B9ACAA19BAf"]'
            HTTP_PORT: "8989"
            RUN_METRICS: "true"
            RUN_HEALTH_CHECK: "true"
            DRY_RUN: "false"
          image: lidofinance/validator-ejector:1.6.0
          ports: []
          volumes:
            - /opt/stereum/validatorejector-41b15ea7-12d4-49f6-8448-8a6164edef36/messages:/app/messages
          user: "2000"
          autoupdate: true
          network: mainnet
          dependencies:
            executionClients:
              - service: GethService
                id: cc1323ce-90a1-440f-8b78-f930a3300b38
            consensusClients:
              - service: LighthouseBeaconService
                id: 62cb879b-b0f0-4ea2-bc13-f606b7f4cfb9
            mevboost: []
            otherServices: []
      become: yes
#EOF
