---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    # ValidatorEjectorService
    - name: Read ValidatorEjectorService file
      slurp:
        src: "/etc/stereum/services/15ce3684-4dbd-4657-8a21-b1243b72b1ca.yaml"
      register: Ejector_service_configuration_raw

    # ValidatorEjectorService2
    - name: Read ValidatorEjectorService file
      slurp:
        src: "/etc/stereum/services/41b15ea7-12d4-49f6-8448-8a6164edef36.yaml"
      register: Ejector_service_configuration2_raw

    # PrysmBeaconService
    - name: Read PrysmBeaconService file
      slurp:
        src: "/etc/stereum/services/d545b944-56d5-dd8f-e6d7-51ad6ecfe7b2.yaml"
      register: PrysmBeacon_service_configuration_raw

    # PrysmValidatorService
    - name: Read PrysmValidatorService file
      slurp:
        src: "/etc/stereum/services/0f8ae6ed-4fb1-ad08-7219-9078373f957b.yaml"
      register: PrysmValdiator_service_configuration_raw

    # RethService
    - name: Read RethService file
      slurp:
        src: "/etc/stereum/services/a9c5f8d8-7487-3038-46da-b72f71caa105.yaml"
      register: Reth_service_configuration_raw

    - name: Parse Service configurations
      set_fact:
        Ejector_service_configuration: "{{ Ejector_service_configuration_raw['content'] | b64decode | from_yaml }}"
        Ejector_service_configuration2: "{{ Ejector_service_configuration2_raw['content'] | b64decode | from_yaml }}"
        PrysmBeacon_service_configuration: "{{ PrysmBeacon_service_configuration_raw['content'] | b64decode | from_yaml }}"
        PrysmValdiator_service_configuration: "{{ PrysmValdiator_service_configuration_raw['content'] | b64decode | from_yaml }}"
        Reth_service_configuration: "{{ Reth_service_configuration_raw['content'] | b64decode | from_yaml }}"

    - debug:
        msg: "{{ Ejector_service_configuration }}"
    - debug:
        msg: "{{ Ejector_service_configuration_raw['content'] | b64decode }}"

    - debug:
        msg: "{{ Ejector_service_configuration2 }}"
    - debug:
        msg: "{{ Ejector_service_configuration2_raw['content'] | b64decode }}"

    - debug:
        msg: "{{ PrysmBeacon_service_configuration }}"
    - debug:
        msg: "{{ PrysmBeacon_service_configuration_raw['content'] | b64decode }}"

    - debug:
        msg: "{{ PrysmValdiator_service_configuration }}"
    - debug:
        msg: "{{ PrysmValdiator_service_configuration_raw['content'] | b64decode }}"

    - debug:
        msg: "{{ Reth_service_configuration }}"
    - debug:
        msg: "{{ Reth_service_configuration_raw['content'] | b64decode }}"

    - assert:
        that:
          - Ejector_service_configuration.env.ORACLE_ADDRESSES_ALLOWLIST | from_yaml | select('match', '0x73181107c8D9ED4ce0bbeF7A0b4ccf3320C41d12') | length == 1
          - Ejector_service_configuration.env.ORACLE_ADDRESSES_ALLOWLIST | from_yaml | select('match', '0x1Ca0fEC59b86F549e1F1184d97cb47794C8Af58d') | length == 0
          - Ejector_service_configuration2.env.ORACLE_ADDRESSES_ALLOWLIST | from_yaml | select('match', '0x73181107c8D9ED4ce0bbeF7A0b4ccf3320C41d12') | length == 1
          - Ejector_service_configuration2.env.ORACLE_ADDRESSES_ALLOWLIST | from_yaml | select('match', '0x1Ca0fEC59b86F549e1F1184d97cb47794C8Af58d') | length == 0
          - PrysmBeacon_service_configuration.command | select('match', 'grpc-gateway') | length == 0
          - PrysmValdiator_service_configuration.command | select('match', 'grpc-gateway') | length == 0
          - PrysmValdiator_service_configuration.command | select('match', '--beacon-rest-api-provider') | length == 1
          - PrysmValdiator_service_configuration.command | select('match', '--enable-beacon-rest-api') | length == 1
          - PrysmValdiator_service_configuration.command | select('match', '--beacon-rpc-gateway-provider') | length == 0
          - Reth_service_configuration.command | select('match', '--engine.legacy') | length == 1
# EOF
