---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  #  Lodestar beacon logs
  - name: Lodestar beacon
    command: "docker logs stereum-1cdcfe4e-3540-11ed-9d60-73ad70b8ccc5"
    register: lodestar_beacon
    until:
      - lodestar_beacon.stdout is search("Validated transition configuration with execution client")
      - lodestar_beacon.stdout is not search("Error updating eth1 chain cache")
    retries: 60
    delay: 10

  #  Erigon Service logs
  - name: Erigon Service
    command: "docker logs stereum-1d938f4c-3540-11ed-b4fd-f72a7f412029"
    register: erigon_logs
    until:
      - erigon_logs.stderr is search("HTTP endpoint opened for Engine API")
      - erigon_logs.stderr is search("Started P2P networking")
    retries: 60
    delay: 10

# EOF