---
- name: Converge
  hosts: all
  vars_files:
  - ../../../../defaults/stereum_defaults.yaml
  vars:
    teku_service: c5a67b18-1fe2-11ed-a441-33f8d671fdfa
    besu_service: c5d0c242-1fe2-11ed-9d4a-0fce20fa52f8
    mevboost_service: c5fa81c2-1fe2-11ed-8fc8-4bcc92882234

  tasks:
    # besu service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: BesuService
              id: "{{ besu_service }}"
              image: hyperledger/besu:{{ stereum_static.defaults.versions.besu }}
              ports:
                - 0.0.0.0:30303:30303/tcp
                - 0.0.0.0:30303:30303/udp
              entrypoint: ["besu"]
              env:
                JAVA_OPTS: -Xmx4g
              command:
                - --network=goerli
                - --data-path=/opt/app/data
                - --data-storage-format=BONSAI
                - --sync-mode=X_SNAP
                - --host-allowlist=*
                - --rpc-http-enabled=true
                - --rpc-http-host=0.0.0.0
                - --rpc-http-cors-origins=*
                - --rpc-http-api=ETH,NET,WEB3
                - --rpc-ws-enabled=true
                - --rpc-ws-api=WEB3,ETH,NET
                - --rpc-ws-host=0.0.0.0
                - --engine-rpc-enabled=true
                - --engine-rpc-port=8551
                - --engine-jwt-enabled=true
                - --engine-jwt-secret=/engine.jwt
                - --engine-host-allowlist=*
              user: "2000"
              volumes:
                - "/opt/app/services/{{ besu_service }}/data:/opt/app/data"
                - "/opt/app/services/{{ besu_service }}/engine.jwt:/engine.jwt"

    # teku beacon & validator service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"

      - name: "Include manage-service"
        include_role:
          name: "manage-service"

      - name: Create keystore password
        copy:
          content: "{{ lookup('password', '/dev/null', seed=inventory_hostname) }}"
          dest: /opt/app/services/{{ teku_service }}/data/teku_api_password.txt
          force: no
        become: yes

      - name: Get teku-api password
        slurp:
          src: "/opt/app/services/{{ teku_service }}/data/teku_api_password.txt"
        register: teku_api_password
        become: yes

      - name: Set variable
        set_fact:
          api_password: "{{ teku_api_password.content | b64decode | trim }}"

      - name: Create keystore file
        command: bash -c "keytool -genkeypair
                          -keystore teku_api_keystore
                          -storetype PKCS12
                          -storepass '{{ api_password }}'
                          -keyalg RSA
                          -keysize 2048
                          -validity 109500
                          -dname 'CN=localhost, OU=MyCompanyUnit, O=MyCompany, L=MyCity, ST=MyState, C=AU'
                          -ext san=dns:localhost,ip:127.0.0.1"
        args:
          chdir: /opt/app/services/{{ teku_service }}/data
        changed_when: false
        become: yes

      - name: Waiting for the services to start properly
        pause:
          seconds: 15

      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: TekuBeaconValidatorService
              id: "{{ teku_service }}"
              image: "consensys/teku:{{ stereum_static.defaults.versions.teku }}"
              ports:
                - 0.0.0.0:9001:9001/tcp
                - 0.0.0.0:9001:9001/udp
              env:
                JAVA_OPTS: -Xmx4g
              entrypoint: ["/opt/teku/bin/teku"]
              command:
                - --network=prater
                - --data-path=/opt/app/data
                - --ee-endpoint=http://stereum-{{ besu_service }}:8551
                - --ee-jwt-secret-file=/engine.jwt
                - --validators-builder-registration-default-enabled=true
                - --validators-proposer-blinded-blocks-enabled=true
                - --validators-proposer-default-fee-recipient=0x5dC29815e46dfb5EAb5C57606f8e2A5FbBdb454e
                - --builder-endpoint=http://stereum-{{ mevboost_service }}:18550
              user: "2000"
              volumes:
                - "/opt/app/services/{{ teku_service }}/data:/opt/app/data"
                - "/opt/app/services/{{ besu_service }}/engine.jwt:/engine.jwt"

    # mevboost service
    - block:
      - set_fact:
          stereum: "{{ stereum_static | combine(stereum_args, recursive=True) }}"
      - name: "Include manage-service"
        include_role:
          name: "manage-service"
      vars:
        stereum_args:
          manage_service:
            save: true
            state: started
            configuration:
              service: MevBoostService
              id: "{{ mevboost_service }}"
              image: flashbots/mev-boost:{{ stereum_static.defaults.versions.mevboost }}
              env: {}
              ports: []
              command: []
              entrypoint:
                - /app/mev-boost
                - -addr
                - 0.0.0.0:18550
                - -goerli
                - -relay-check
                - -relays
                - "{{ stereum_static.defaults.relay.goerli }}"
              user: "2000"
              volumes: []

# EOF